spring:
  output:
    ansi:
      enabled: always
  message:
    basename: messages
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8088

logging:
  level:
    org.springframework: DEBUG

menagement:
  endpoints:
    web:
      exposure:
        include: "*"