spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/jpashop
    username: sa
    password: jpashop
    driver-class-name: org.h2.Driver
  output:
    ansi:
      enabled: always

  jpa:
    hibernate:
      ddl-auto: create # 자동으로 테이블을 만들어주는 모드
    properties:
      hibernate:
#        show_spl: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 쿼리 파라미터 로그 남기기
